version: '3'
services:
  postgres:
    image: postgres:14
    container_name: boln
    environment:
      POSTGRES_DB: boln
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
