# Generated by Django 4.2.6 on 2024-10-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='rating',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
